// examples/react/src/App.jsx
import React, { useState } from 'react';
import Button from './components/Button';
import Heading from './components/Heading';
import Link from './components/Link';

function App() {
  const [clickCount, setClickCount] = useState(0);

  const handleButtonClick = () => {
    setClickCount(prev => prev + 1);
  };

  return (
    <div className="container">
      <Heading level={2}>React Testing Demo</Heading>
      
      <Heading level={1}>Welcome to our simple React app!</Heading>
      
      <p>This is a simple page with buttons, headings, and links for testing npm packages.</p>
      
      <Heading level={3}>Interactive Elements</Heading>
      
      <div>
        <Button onClick={handleButtonClick}>
          Click me! (Clicked {clickCount} times)
        </Button>
        
        <Button onClick={() => alert('Hello from React!')}>
          Show Alert
        </Button>
      </div>
      
      <Heading level={3}>Useful Links</Heading>
      
      <div>
        <Link href="https://reactjs.org">React Documentation</Link>
        <Link href="https://testing-library.com">Testing Library</Link>
        <Link href="https://jestjs.io">Jest Testing Framework</Link>
      </div>
      
      <Heading level={3}>About</Heading>
      
      <p>This app is designed to test npm packages with React components. It includes:</p>
      <ul>
        <li>Button components with click handlers</li>
        <li>Heading components with different levels</li>
        <li>Link components with external URLs</li>
        <li>State management with useState</li>
      </ul>
    </div>
  );
}

export default App;

// examples/vue/src/App.vue
<template>
  <div class="container">
    <Heading tag="h2">Vue Testing Demo</Heading>
    <Heading tag="h1">Welcome to our simple Vue app!</Heading>
    
    <p>This is a simple page with buttons, headings, and links for testing npm packages.</p>
    
    <Heading tag="h3">Interactive Elements</Heading>
    <div>
      <Button @click="incrementCounter">
        Click me! (Clicked {{ counter }} times)
      </Button>
      <Button @click="showAlert">
        Show Alert
      </Button>
    </div>
    
    <Heading tag="h3">Useful Links</Heading>
    <div>
      <Link href="https://vuejs.org">Vue Documentation</Link>
      <Link href="https://testing-library.com">Testing Library</Link>
      <Link href="https://vitest.dev">Vitest Testing Framework</Link>
    </div>
    
    <Heading tag="h3">About</Heading>
    <p>This app is designed to test npm packages with Vue components. It includes:</p>
    <ul>
      <li>Button components with click handlers</li>
      <li>Heading components with different levels</li>
      <li>Link components with external URLs</li>
      <li>State management with Composition API</li>
    </ul>
  </div>
</template>

<script>
import { ref } from 'vue'
import Button from './components/Button.vue'
import Heading from './components/Heading.vue'
import Link from './components/Link.vue'

export default {
  name: 'App',
  components: {
    Button,
    Heading,
    Link
  },
  setup() {
    const counter = ref(0)
    
    const incrementCounter = () => {
      counter.value++
    }
    
    const showAlert = () => {
      alert('Hello from Vue!')
    }
    
    return {
      counter,
      incrementCounter,
      showAlert
    }
  }
}
</script>
